name: Keep Workflow Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # 매 5분마다 트리거 (UTC 기준)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing (Keep GitHub Actions active)
        run: echo "Keep GitHub Actions alive"
